### ISSUE TITLE
More styling options

### ISSUE THREAD

**Issue by utkuturk** [montesmariana/glossr#2]
Hi @montesmariana, awesome package! Thank you very much, it helps a lot with quarto!

I was having certain spacing problems between examples in lists. I handled it by adding certain linguex settings to the preamble. I am writing this issue so that additional styling options can be added to the `use_glossr()`. Also, other people that may have similar problem can find some work around like I had.

Thank you for your work!

---
My YAML: 
```YAML
---
title: "title"
date: "`r format(Sys.time(), '%B %d, %Y')`"
author: "Utku Turk"
format: 
  pdf: 
    pdf-engine: xelatex
    toc: false
    number-sections: true
    fontsize: 10pt
    documentclass: article
    cap-location: bottom
    papersize: a4
    geometry: 
      - margin=0.5in
    execute:
      echo: false
      warning: false
    fig-align: center
    fig-format: retina
    fig-dpi: 320
    bibliography: ref.bib
    biblio-style: apacite
    keep-md: true
    keep-tex: true
    latex-auto-install: true
    latex-clean: true
    latex-tinytex: false
    include-before-body: preamble.tex
---
```

Inside the preamble.tex, I had something similar to the following.

```LaTeX
\lingset{
    aboveglftskip=0pt,
    belowglpreambleskip=0pt,
    belowpreambleskip=0pt,
    extraglskip=-16pt,
    Everyex={\parskip=6pt},
    everygla={}
}
```

My output without the preamble was as the following:

<img width="377" alt="Screenshot 2022-11-03 at 9 51 24 PM" src="https://user-images.githubusercontent.com/34624245/199868031-deca3c47-aa7e-47e8-b32a-d5777bb6bb96.png">

After the preamble edit my output was like this: 

<img width="418" alt="image" src="https://user-images.githubusercontent.com/34624245/199868113-272198f9-f66a-44cb-bb3b-2d7115e70f5d.png">
